import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { useLocale } from "next-intl"
import "./globals.css"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Daniel Bueno | Portfolio",
  description: "Generated by create next app" 
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  const locale = useLocale()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
